// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.4
// source: api/protobuf-spec/connection_resource_v1.proto

package resourcepb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Interest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Color string `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Emoji string `protobuf:"bytes,3,opt,name=emoji,proto3" json:"emoji,omitempty"`
	Id    string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Interest) Reset() {
	*x = Interest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Interest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interest) ProtoMessage() {}

func (x *Interest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interest.ProtoReflect.Descriptor instead.
func (*Interest) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_connection_resource_v1_proto_rawDescGZIP(), []int{0}
}

func (x *Interest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Interest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Interest) GetEmoji() string {
	if x != nil {
		return x.Emoji
	}
	return ""
}

func (x *Interest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Service struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Color string `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Emoji string `protobuf:"bytes,3,opt,name=emoji,proto3" json:"emoji,omitempty"`
	Id    string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Service) Reset() {
	*x = Service{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_connection_resource_v1_proto_rawDescGZIP(), []int{1}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Service) GetEmoji() string {
	if x != nil {
		return x.Emoji
	}
	return ""
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetInterestsRequests struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InterestsId []string `protobuf:"bytes,1,rep,name=interests_id,json=interestsId,proto3" json:"interests_id,omitempty"`
}

func (x *GetInterestsRequests) Reset() {
	*x = GetInterestsRequests{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInterestsRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInterestsRequests) ProtoMessage() {}

func (x *GetInterestsRequests) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInterestsRequests.ProtoReflect.Descriptor instead.
func (*GetInterestsRequests) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_connection_resource_v1_proto_rawDescGZIP(), []int{2}
}

func (x *GetInterestsRequests) GetInterestsId() []string {
	if x != nil {
		return x.InterestsId
	}
	return nil
}

type GetInterestsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Interests []*Interest `protobuf:"bytes,1,rep,name=interests,proto3" json:"interests,omitempty"`
}

func (x *GetInterestsResponse) Reset() {
	*x = GetInterestsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInterestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInterestsResponse) ProtoMessage() {}

func (x *GetInterestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInterestsResponse.ProtoReflect.Descriptor instead.
func (*GetInterestsResponse) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_connection_resource_v1_proto_rawDescGZIP(), []int{3}
}

func (x *GetInterestsResponse) GetInterests() []*Interest {
	if x != nil {
		return x.Interests
	}
	return nil
}

type GetAllInterestsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InterestsId []string `protobuf:"bytes,1,rep,name=interests_id,json=interestsId,proto3" json:"interests_id,omitempty"`
}

func (x *GetAllInterestsResponse) Reset() {
	*x = GetAllInterestsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllInterestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllInterestsResponse) ProtoMessage() {}

func (x *GetAllInterestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllInterestsResponse.ProtoReflect.Descriptor instead.
func (*GetAllInterestsResponse) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_connection_resource_v1_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllInterestsResponse) GetInterestsId() []string {
	if x != nil {
		return x.InterestsId
	}
	return nil
}

type GetUserInterestsRequests struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetUserInterestsRequests) Reset() {
	*x = GetUserInterestsRequests{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInterestsRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInterestsRequests) ProtoMessage() {}

func (x *GetUserInterestsRequests) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInterestsRequests.ProtoReflect.Descriptor instead.
func (*GetUserInterestsRequests) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_connection_resource_v1_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserInterestsRequests) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SharedInterestsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InterestIds []string `protobuf:"bytes,1,rep,name=interest_ids,json=interestIds,proto3" json:"interest_ids,omitempty"`
}

func (x *SharedInterestsResponse) Reset() {
	*x = SharedInterestsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SharedInterestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedInterestsResponse) ProtoMessage() {}

func (x *SharedInterestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedInterestsResponse.ProtoReflect.Descriptor instead.
func (*SharedInterestsResponse) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_connection_resource_v1_proto_rawDescGZIP(), []int{6}
}

func (x *SharedInterestsResponse) GetInterestIds() []string {
	if x != nil {
		return x.InterestIds
	}
	return nil
}

type SharedInterestsRequests struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserFromId string `protobuf:"bytes,1,opt,name=user_from_id,json=userFromId,proto3" json:"user_from_id,omitempty"`
	UserToId   string `protobuf:"bytes,2,opt,name=user_to_id,json=userToId,proto3" json:"user_to_id,omitempty"`
}

func (x *SharedInterestsRequests) Reset() {
	*x = SharedInterestsRequests{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SharedInterestsRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedInterestsRequests) ProtoMessage() {}

func (x *SharedInterestsRequests) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedInterestsRequests.ProtoReflect.Descriptor instead.
func (*SharedInterestsRequests) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_connection_resource_v1_proto_rawDescGZIP(), []int{7}
}

func (x *SharedInterestsRequests) GetUserFromId() string {
	if x != nil {
		return x.UserFromId
	}
	return ""
}

func (x *SharedInterestsRequests) GetUserToId() string {
	if x != nil {
		return x.UserToId
	}
	return ""
}

type GetUserInterestsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InterestsId []string `protobuf:"bytes,1,rep,name=interests_id,json=interestsId,proto3" json:"interests_id,omitempty"`
}

func (x *GetUserInterestsResponse) Reset() {
	*x = GetUserInterestsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInterestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInterestsResponse) ProtoMessage() {}

func (x *GetUserInterestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInterestsResponse.ProtoReflect.Descriptor instead.
func (*GetUserInterestsResponse) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_connection_resource_v1_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserInterestsResponse) GetInterestsId() []string {
	if x != nil {
		return x.InterestsId
	}
	return nil
}

type ConnectUserInterestsRequests struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InterestsId []string `protobuf:"bytes,2,rep,name=interests_id,json=interestsId,proto3" json:"interests_id,omitempty"`
}

func (x *ConnectUserInterestsRequests) Reset() {
	*x = ConnectUserInterestsRequests{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectUserInterestsRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectUserInterestsRequests) ProtoMessage() {}

func (x *ConnectUserInterestsRequests) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectUserInterestsRequests.ProtoReflect.Descriptor instead.
func (*ConnectUserInterestsRequests) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_connection_resource_v1_proto_rawDescGZIP(), []int{9}
}

func (x *ConnectUserInterestsRequests) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConnectUserInterestsRequests) GetInterestsId() []string {
	if x != nil {
		return x.InterestsId
	}
	return nil
}

type GetServicesRequests struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServicesId []string `protobuf:"bytes,1,rep,name=services_id,json=servicesId,proto3" json:"services_id,omitempty"`
}

func (x *GetServicesRequests) Reset() {
	*x = GetServicesRequests{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServicesRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServicesRequests) ProtoMessage() {}

func (x *GetServicesRequests) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServicesRequests.ProtoReflect.Descriptor instead.
func (*GetServicesRequests) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_connection_resource_v1_proto_rawDescGZIP(), []int{10}
}

func (x *GetServicesRequests) GetServicesId() []string {
	if x != nil {
		return x.ServicesId
	}
	return nil
}

type GetServicesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Services []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
}

func (x *GetServicesResponse) Reset() {
	*x = GetServicesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServicesResponse) ProtoMessage() {}

func (x *GetServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServicesResponse.ProtoReflect.Descriptor instead.
func (*GetServicesResponse) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_connection_resource_v1_proto_rawDescGZIP(), []int{11}
}

func (x *GetServicesResponse) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type GetAllServicesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServicesId []string `protobuf:"bytes,1,rep,name=services_id,json=servicesId,proto3" json:"services_id,omitempty"`
}

func (x *GetAllServicesResponse) Reset() {
	*x = GetAllServicesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllServicesResponse) ProtoMessage() {}

func (x *GetAllServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllServicesResponse.ProtoReflect.Descriptor instead.
func (*GetAllServicesResponse) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_connection_resource_v1_proto_rawDescGZIP(), []int{12}
}

func (x *GetAllServicesResponse) GetServicesId() []string {
	if x != nil {
		return x.ServicesId
	}
	return nil
}

type UserOfferServicesRequests struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *UserOfferServicesRequests) Reset() {
	*x = UserOfferServicesRequests{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOfferServicesRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOfferServicesRequests) ProtoMessage() {}

func (x *UserOfferServicesRequests) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOfferServicesRequests.ProtoReflect.Descriptor instead.
func (*UserOfferServicesRequests) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_connection_resource_v1_proto_rawDescGZIP(), []int{13}
}

func (x *UserOfferServicesRequests) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserOfferServicesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServicesId []string `protobuf:"bytes,1,rep,name=services_id,json=servicesId,proto3" json:"services_id,omitempty"`
}

func (x *UserOfferServicesResponse) Reset() {
	*x = UserOfferServicesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOfferServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOfferServicesResponse) ProtoMessage() {}

func (x *UserOfferServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOfferServicesResponse.ProtoReflect.Descriptor instead.
func (*UserOfferServicesResponse) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_connection_resource_v1_proto_rawDescGZIP(), []int{14}
}

func (x *UserOfferServicesResponse) GetServicesId() []string {
	if x != nil {
		return x.ServicesId
	}
	return nil
}

type UserRequestedServicesRequests struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *UserRequestedServicesRequests) Reset() {
	*x = UserRequestedServicesRequests{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRequestedServicesRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequestedServicesRequests) ProtoMessage() {}

func (x *UserRequestedServicesRequests) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequestedServicesRequests.ProtoReflect.Descriptor instead.
func (*UserRequestedServicesRequests) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_connection_resource_v1_proto_rawDescGZIP(), []int{15}
}

func (x *UserRequestedServicesRequests) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserRequestedServicesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServicesId []string `protobuf:"bytes,1,rep,name=services_id,json=servicesId,proto3" json:"services_id,omitempty"`
}

func (x *UserRequestedServicesResponse) Reset() {
	*x = UserRequestedServicesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRequestedServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequestedServicesResponse) ProtoMessage() {}

func (x *UserRequestedServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequestedServicesResponse.ProtoReflect.Descriptor instead.
func (*UserRequestedServicesResponse) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_connection_resource_v1_proto_rawDescGZIP(), []int{16}
}

func (x *UserRequestedServicesResponse) GetServicesId() []string {
	if x != nil {
		return x.ServicesId
	}
	return nil
}

type ConnectUserOfferServicesRequests struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ServicesId []string `protobuf:"bytes,2,rep,name=services_id,json=servicesId,proto3" json:"services_id,omitempty"`
}

func (x *ConnectUserOfferServicesRequests) Reset() {
	*x = ConnectUserOfferServicesRequests{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectUserOfferServicesRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectUserOfferServicesRequests) ProtoMessage() {}

func (x *ConnectUserOfferServicesRequests) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectUserOfferServicesRequests.ProtoReflect.Descriptor instead.
func (*ConnectUserOfferServicesRequests) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_connection_resource_v1_proto_rawDescGZIP(), []int{17}
}

func (x *ConnectUserOfferServicesRequests) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConnectUserOfferServicesRequests) GetServicesId() []string {
	if x != nil {
		return x.ServicesId
	}
	return nil
}

type ConnectUserRequestedServicesRequests struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ServicesId []string `protobuf:"bytes,2,rep,name=services_id,json=servicesId,proto3" json:"services_id,omitempty"`
}

func (x *ConnectUserRequestedServicesRequests) Reset() {
	*x = ConnectUserRequestedServicesRequests{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectUserRequestedServicesRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectUserRequestedServicesRequests) ProtoMessage() {}

func (x *ConnectUserRequestedServicesRequests) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectUserRequestedServicesRequests.ProtoReflect.Descriptor instead.
func (*ConnectUserRequestedServicesRequests) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_connection_resource_v1_proto_rawDescGZIP(), []int{18}
}

func (x *ConnectUserRequestedServicesRequests) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConnectUserRequestedServicesRequests) GetServicesId() []string {
	if x != nil {
		return x.ServicesId
	}
	return nil
}

var File_api_protobuf_spec_connection_resource_v1_proto protoreflect.FileDescriptor

var file_api_protobuf_spec_connection_resource_v1_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2d, 0x73,
	0x70, 0x65, 0x63, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x14, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x5a, 0x0a, 0x08, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x6f,
	0x6a, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x59, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x39, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65,
	0x73, 0x74, 0x73, 0x49, 0x64, 0x22, 0x54, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a,
	0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74,
	0x52, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x22, 0x3c, 0x0a, 0x17, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65,
	0x73, 0x74, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x49, 0x64, 0x22, 0x33, 0x0a, 0x18, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3c,
	0x0a, 0x17, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x49, 0x64, 0x73, 0x22, 0x59, 0x0a, 0x17,
	0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x20, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75,
	0x73, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x0a, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x54, 0x6f, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x65, 0x73, 0x74, 0x73, 0x49, 0x64, 0x22, 0x5a, 0x0a, 0x1c, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73,
	0x49, 0x64, 0x22, 0x36, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x49, 0x64, 0x22, 0x50, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x39, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x39, 0x0a, 0x16,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x19, 0x55, 0x73, 0x65, 0x72, 0x4f,
	0x66, 0x66, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3c, 0x0a,
	0x19, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x49, 0x64, 0x22, 0x38, 0x0a, 0x1d, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x40, 0x0a, 0x1d, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x49, 0x64, 0x22, 0x5c, 0x0a, 0x20, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x49, 0x64, 0x22, 0x60, 0x0a, 0x24, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x49, 0x64, 0x32, 0xd0, 0x09, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x68, 0x0a, 0x0c, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x12, 0x2a, 0x2e, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x1a, 0x2a, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x71, 0x0a, 0x0f, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x12, 0x2d, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e,
	0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x1a, 0x2d, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x53,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x2d, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x74, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x12, 0x2e, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x1a, 0x2e, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x64, 0x0a, 0x14, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73,
	0x74, 0x73, 0x12, 0x32, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x12, 0x65, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12,
	0x29, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x1a, 0x29, 0x2e, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x2c, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x7a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x2f, 0x2e, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x1a, 0x2f, 0x2e, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x86, 0x01,
	0x0a, 0x18, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x33, 0x2e, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x1a,
	0x33, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6c, 0x0a, 0x18, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x12, 0x36, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x12, 0x74, 0x0a, 0x1c, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x12, 0x3a, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x23, 0x5a, 0x21, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x70, 0x62, 0x3b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_protobuf_spec_connection_resource_v1_proto_rawDescOnce sync.Once
	file_api_protobuf_spec_connection_resource_v1_proto_rawDescData = file_api_protobuf_spec_connection_resource_v1_proto_rawDesc
)

func file_api_protobuf_spec_connection_resource_v1_proto_rawDescGZIP() []byte {
	file_api_protobuf_spec_connection_resource_v1_proto_rawDescOnce.Do(func() {
		file_api_protobuf_spec_connection_resource_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_protobuf_spec_connection_resource_v1_proto_rawDescData)
	})
	return file_api_protobuf_spec_connection_resource_v1_proto_rawDescData
}

var file_api_protobuf_spec_connection_resource_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_protobuf_spec_connection_resource_v1_proto_goTypes = []interface{}{
	(*Interest)(nil),                             // 0: connections.resource.Interest
	(*Service)(nil),                              // 1: connections.resource.Service
	(*GetInterestsRequests)(nil),                 // 2: connections.resource.GetInterestsRequests
	(*GetInterestsResponse)(nil),                 // 3: connections.resource.GetInterestsResponse
	(*GetAllInterestsResponse)(nil),              // 4: connections.resource.GetAllInterestsResponse
	(*GetUserInterestsRequests)(nil),             // 5: connections.resource.GetUserInterestsRequests
	(*SharedInterestsResponse)(nil),              // 6: connections.resource.SharedInterestsResponse
	(*SharedInterestsRequests)(nil),              // 7: connections.resource.SharedInterestsRequests
	(*GetUserInterestsResponse)(nil),             // 8: connections.resource.GetUserInterestsResponse
	(*ConnectUserInterestsRequests)(nil),         // 9: connections.resource.ConnectUserInterestsRequests
	(*GetServicesRequests)(nil),                  // 10: connections.resource.GetServicesRequests
	(*GetServicesResponse)(nil),                  // 11: connections.resource.GetServicesResponse
	(*GetAllServicesResponse)(nil),               // 12: connections.resource.GetAllServicesResponse
	(*UserOfferServicesRequests)(nil),            // 13: connections.resource.UserOfferServicesRequests
	(*UserOfferServicesResponse)(nil),            // 14: connections.resource.UserOfferServicesResponse
	(*UserRequestedServicesRequests)(nil),        // 15: connections.resource.UserRequestedServicesRequests
	(*UserRequestedServicesResponse)(nil),        // 16: connections.resource.UserRequestedServicesResponse
	(*ConnectUserOfferServicesRequests)(nil),     // 17: connections.resource.ConnectUserOfferServicesRequests
	(*ConnectUserRequestedServicesRequests)(nil), // 18: connections.resource.ConnectUserRequestedServicesRequests
	(*empty.Empty)(nil),                          // 19: google.protobuf.Empty
}
var file_api_protobuf_spec_connection_resource_v1_proto_depIdxs = []int32{
	0,  // 0: connections.resource.GetInterestsResponse.interests:type_name -> connections.resource.Interest
	1,  // 1: connections.resource.GetServicesResponse.services:type_name -> connections.resource.Service
	2,  // 2: connections.resource.ResourceService.GetInterests:input_type -> connections.resource.GetInterestsRequests
	7,  // 3: connections.resource.ResourceService.SharedInterests:input_type -> connections.resource.SharedInterestsRequests
	19, // 4: connections.resource.ResourceService.GetAllInterests:input_type -> google.protobuf.Empty
	5,  // 5: connections.resource.ResourceService.GetUserInterests:input_type -> connections.resource.GetUserInterestsRequests
	9,  // 6: connections.resource.ResourceService.ConnectUserInterests:input_type -> connections.resource.ConnectUserInterestsRequests
	10, // 7: connections.resource.ResourceService.GetServices:input_type -> connections.resource.GetServicesRequests
	19, // 8: connections.resource.ResourceService.GetAllServices:input_type -> google.protobuf.Empty
	13, // 9: connections.resource.ResourceService.GetUserOfferServices:input_type -> connections.resource.UserOfferServicesRequests
	15, // 10: connections.resource.ResourceService.GetUserRequestedServices:input_type -> connections.resource.UserRequestedServicesRequests
	17, // 11: connections.resource.ResourceService.ConnectUserOfferServices:input_type -> connections.resource.ConnectUserOfferServicesRequests
	18, // 12: connections.resource.ResourceService.ConnectUserRequestedServices:input_type -> connections.resource.ConnectUserRequestedServicesRequests
	3,  // 13: connections.resource.ResourceService.GetInterests:output_type -> connections.resource.GetInterestsResponse
	6,  // 14: connections.resource.ResourceService.SharedInterests:output_type -> connections.resource.SharedInterestsResponse
	4,  // 15: connections.resource.ResourceService.GetAllInterests:output_type -> connections.resource.GetAllInterestsResponse
	8,  // 16: connections.resource.ResourceService.GetUserInterests:output_type -> connections.resource.GetUserInterestsResponse
	19, // 17: connections.resource.ResourceService.ConnectUserInterests:output_type -> google.protobuf.Empty
	11, // 18: connections.resource.ResourceService.GetServices:output_type -> connections.resource.GetServicesResponse
	12, // 19: connections.resource.ResourceService.GetAllServices:output_type -> connections.resource.GetAllServicesResponse
	14, // 20: connections.resource.ResourceService.GetUserOfferServices:output_type -> connections.resource.UserOfferServicesResponse
	16, // 21: connections.resource.ResourceService.GetUserRequestedServices:output_type -> connections.resource.UserRequestedServicesResponse
	19, // 22: connections.resource.ResourceService.ConnectUserOfferServices:output_type -> google.protobuf.Empty
	19, // 23: connections.resource.ResourceService.ConnectUserRequestedServices:output_type -> google.protobuf.Empty
	13, // [13:24] is the sub-list for method output_type
	2,  // [2:13] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_protobuf_spec_connection_resource_v1_proto_init() }
func file_api_protobuf_spec_connection_resource_v1_proto_init() {
	if File_api_protobuf_spec_connection_resource_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Interest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Service); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInterestsRequests); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInterestsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllInterestsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserInterestsRequests); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SharedInterestsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SharedInterestsRequests); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserInterestsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectUserInterestsRequests); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServicesRequests); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServicesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllServicesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserOfferServicesRequests); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserOfferServicesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRequestedServicesRequests); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRequestedServicesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectUserOfferServicesRequests); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_connection_resource_v1_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectUserRequestedServicesRequests); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_protobuf_spec_connection_resource_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_protobuf_spec_connection_resource_v1_proto_goTypes,
		DependencyIndexes: file_api_protobuf_spec_connection_resource_v1_proto_depIdxs,
		MessageInfos:      file_api_protobuf_spec_connection_resource_v1_proto_msgTypes,
	}.Build()
	File_api_protobuf_spec_connection_resource_v1_proto = out.File
	file_api_protobuf_spec_connection_resource_v1_proto_rawDesc = nil
	file_api_protobuf_spec_connection_resource_v1_proto_goTypes = nil
	file_api_protobuf_spec_connection_resource_v1_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ResourceServiceClient is the client API for ResourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResourceServiceClient interface {
	GetInterests(ctx context.Context, in *GetInterestsRequests, opts ...grpc.CallOption) (*GetInterestsResponse, error)
	SharedInterests(ctx context.Context, in *SharedInterestsRequests, opts ...grpc.CallOption) (*SharedInterestsResponse, error)
	GetAllInterests(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetAllInterestsResponse, error)
	GetUserInterests(ctx context.Context, in *GetUserInterestsRequests, opts ...grpc.CallOption) (*GetUserInterestsResponse, error)
	ConnectUserInterests(ctx context.Context, in *ConnectUserInterestsRequests, opts ...grpc.CallOption) (*empty.Empty, error)
	GetServices(ctx context.Context, in *GetServicesRequests, opts ...grpc.CallOption) (*GetServicesResponse, error)
	GetAllServices(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetAllServicesResponse, error)
	GetUserOfferServices(ctx context.Context, in *UserOfferServicesRequests, opts ...grpc.CallOption) (*UserOfferServicesResponse, error)
	GetUserRequestedServices(ctx context.Context, in *UserRequestedServicesRequests, opts ...grpc.CallOption) (*UserRequestedServicesResponse, error)
	ConnectUserOfferServices(ctx context.Context, in *ConnectUserOfferServicesRequests, opts ...grpc.CallOption) (*empty.Empty, error)
	ConnectUserRequestedServices(ctx context.Context, in *ConnectUserRequestedServicesRequests, opts ...grpc.CallOption) (*empty.Empty, error)
}

type resourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceServiceClient(cc grpc.ClientConnInterface) ResourceServiceClient {
	return &resourceServiceClient{cc}
}

func (c *resourceServiceClient) GetInterests(ctx context.Context, in *GetInterestsRequests, opts ...grpc.CallOption) (*GetInterestsResponse, error) {
	out := new(GetInterestsResponse)
	err := c.cc.Invoke(ctx, "/connections.resource.ResourceService/GetInterests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) SharedInterests(ctx context.Context, in *SharedInterestsRequests, opts ...grpc.CallOption) (*SharedInterestsResponse, error) {
	out := new(SharedInterestsResponse)
	err := c.cc.Invoke(ctx, "/connections.resource.ResourceService/SharedInterests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) GetAllInterests(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetAllInterestsResponse, error) {
	out := new(GetAllInterestsResponse)
	err := c.cc.Invoke(ctx, "/connections.resource.ResourceService/GetAllInterests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) GetUserInterests(ctx context.Context, in *GetUserInterestsRequests, opts ...grpc.CallOption) (*GetUserInterestsResponse, error) {
	out := new(GetUserInterestsResponse)
	err := c.cc.Invoke(ctx, "/connections.resource.ResourceService/GetUserInterests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) ConnectUserInterests(ctx context.Context, in *ConnectUserInterestsRequests, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/connections.resource.ResourceService/ConnectUserInterests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) GetServices(ctx context.Context, in *GetServicesRequests, opts ...grpc.CallOption) (*GetServicesResponse, error) {
	out := new(GetServicesResponse)
	err := c.cc.Invoke(ctx, "/connections.resource.ResourceService/GetServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) GetAllServices(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetAllServicesResponse, error) {
	out := new(GetAllServicesResponse)
	err := c.cc.Invoke(ctx, "/connections.resource.ResourceService/GetAllServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) GetUserOfferServices(ctx context.Context, in *UserOfferServicesRequests, opts ...grpc.CallOption) (*UserOfferServicesResponse, error) {
	out := new(UserOfferServicesResponse)
	err := c.cc.Invoke(ctx, "/connections.resource.ResourceService/GetUserOfferServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) GetUserRequestedServices(ctx context.Context, in *UserRequestedServicesRequests, opts ...grpc.CallOption) (*UserRequestedServicesResponse, error) {
	out := new(UserRequestedServicesResponse)
	err := c.cc.Invoke(ctx, "/connections.resource.ResourceService/GetUserRequestedServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) ConnectUserOfferServices(ctx context.Context, in *ConnectUserOfferServicesRequests, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/connections.resource.ResourceService/ConnectUserOfferServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) ConnectUserRequestedServices(ctx context.Context, in *ConnectUserRequestedServicesRequests, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/connections.resource.ResourceService/ConnectUserRequestedServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceServiceServer is the server API for ResourceService service.
type ResourceServiceServer interface {
	GetInterests(context.Context, *GetInterestsRequests) (*GetInterestsResponse, error)
	SharedInterests(context.Context, *SharedInterestsRequests) (*SharedInterestsResponse, error)
	GetAllInterests(context.Context, *empty.Empty) (*GetAllInterestsResponse, error)
	GetUserInterests(context.Context, *GetUserInterestsRequests) (*GetUserInterestsResponse, error)
	ConnectUserInterests(context.Context, *ConnectUserInterestsRequests) (*empty.Empty, error)
	GetServices(context.Context, *GetServicesRequests) (*GetServicesResponse, error)
	GetAllServices(context.Context, *empty.Empty) (*GetAllServicesResponse, error)
	GetUserOfferServices(context.Context, *UserOfferServicesRequests) (*UserOfferServicesResponse, error)
	GetUserRequestedServices(context.Context, *UserRequestedServicesRequests) (*UserRequestedServicesResponse, error)
	ConnectUserOfferServices(context.Context, *ConnectUserOfferServicesRequests) (*empty.Empty, error)
	ConnectUserRequestedServices(context.Context, *ConnectUserRequestedServicesRequests) (*empty.Empty, error)
}

// UnimplementedResourceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedResourceServiceServer struct {
}

func (*UnimplementedResourceServiceServer) GetInterests(context.Context, *GetInterestsRequests) (*GetInterestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInterests not implemented")
}
func (*UnimplementedResourceServiceServer) SharedInterests(context.Context, *SharedInterestsRequests) (*SharedInterestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SharedInterests not implemented")
}
func (*UnimplementedResourceServiceServer) GetAllInterests(context.Context, *empty.Empty) (*GetAllInterestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllInterests not implemented")
}
func (*UnimplementedResourceServiceServer) GetUserInterests(context.Context, *GetUserInterestsRequests) (*GetUserInterestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInterests not implemented")
}
func (*UnimplementedResourceServiceServer) ConnectUserInterests(context.Context, *ConnectUserInterestsRequests) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectUserInterests not implemented")
}
func (*UnimplementedResourceServiceServer) GetServices(context.Context, *GetServicesRequests) (*GetServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServices not implemented")
}
func (*UnimplementedResourceServiceServer) GetAllServices(context.Context, *empty.Empty) (*GetAllServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllServices not implemented")
}
func (*UnimplementedResourceServiceServer) GetUserOfferServices(context.Context, *UserOfferServicesRequests) (*UserOfferServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserOfferServices not implemented")
}
func (*UnimplementedResourceServiceServer) GetUserRequestedServices(context.Context, *UserRequestedServicesRequests) (*UserRequestedServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserRequestedServices not implemented")
}
func (*UnimplementedResourceServiceServer) ConnectUserOfferServices(context.Context, *ConnectUserOfferServicesRequests) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectUserOfferServices not implemented")
}
func (*UnimplementedResourceServiceServer) ConnectUserRequestedServices(context.Context, *ConnectUserRequestedServicesRequests) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectUserRequestedServices not implemented")
}

func RegisterResourceServiceServer(s *grpc.Server, srv ResourceServiceServer) {
	s.RegisterService(&_ResourceService_serviceDesc, srv)
}

func _ResourceService_GetInterests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInterestsRequests)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetInterests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connections.resource.ResourceService/GetInterests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetInterests(ctx, req.(*GetInterestsRequests))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_SharedInterests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SharedInterestsRequests)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).SharedInterests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connections.resource.ResourceService/SharedInterests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).SharedInterests(ctx, req.(*SharedInterestsRequests))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_GetAllInterests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetAllInterests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connections.resource.ResourceService/GetAllInterests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetAllInterests(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_GetUserInterests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInterestsRequests)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetUserInterests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connections.resource.ResourceService/GetUserInterests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetUserInterests(ctx, req.(*GetUserInterestsRequests))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_ConnectUserInterests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectUserInterestsRequests)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).ConnectUserInterests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connections.resource.ResourceService/ConnectUserInterests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).ConnectUserInterests(ctx, req.(*ConnectUserInterestsRequests))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_GetServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServicesRequests)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connections.resource.ResourceService/GetServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetServices(ctx, req.(*GetServicesRequests))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_GetAllServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetAllServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connections.resource.ResourceService/GetAllServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetAllServices(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_GetUserOfferServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserOfferServicesRequests)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetUserOfferServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connections.resource.ResourceService/GetUserOfferServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetUserOfferServices(ctx, req.(*UserOfferServicesRequests))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_GetUserRequestedServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequestedServicesRequests)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetUserRequestedServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connections.resource.ResourceService/GetUserRequestedServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetUserRequestedServices(ctx, req.(*UserRequestedServicesRequests))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_ConnectUserOfferServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectUserOfferServicesRequests)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).ConnectUserOfferServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connections.resource.ResourceService/ConnectUserOfferServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).ConnectUserOfferServices(ctx, req.(*ConnectUserOfferServicesRequests))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_ConnectUserRequestedServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectUserRequestedServicesRequests)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).ConnectUserRequestedServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connections.resource.ResourceService/ConnectUserRequestedServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).ConnectUserRequestedServices(ctx, req.(*ConnectUserRequestedServicesRequests))
	}
	return interceptor(ctx, in, info, handler)
}

var _ResourceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "connections.resource.ResourceService",
	HandlerType: (*ResourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInterests",
			Handler:    _ResourceService_GetInterests_Handler,
		},
		{
			MethodName: "SharedInterests",
			Handler:    _ResourceService_SharedInterests_Handler,
		},
		{
			MethodName: "GetAllInterests",
			Handler:    _ResourceService_GetAllInterests_Handler,
		},
		{
			MethodName: "GetUserInterests",
			Handler:    _ResourceService_GetUserInterests_Handler,
		},
		{
			MethodName: "ConnectUserInterests",
			Handler:    _ResourceService_ConnectUserInterests_Handler,
		},
		{
			MethodName: "GetServices",
			Handler:    _ResourceService_GetServices_Handler,
		},
		{
			MethodName: "GetAllServices",
			Handler:    _ResourceService_GetAllServices_Handler,
		},
		{
			MethodName: "GetUserOfferServices",
			Handler:    _ResourceService_GetUserOfferServices_Handler,
		},
		{
			MethodName: "GetUserRequestedServices",
			Handler:    _ResourceService_GetUserRequestedServices_Handler,
		},
		{
			MethodName: "ConnectUserOfferServices",
			Handler:    _ResourceService_ConnectUserOfferServices_Handler,
		},
		{
			MethodName: "ConnectUserRequestedServices",
			Handler:    _ResourceService_ConnectUserRequestedServices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/protobuf-spec/connection_resource_v1.proto",
}
